// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YakShop.Data;

#nullable disable

namespace YakShop.Migrations
{
    [DbContext(typeof(YakShopContext))]
    [Migration("20230914083332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YakShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<double>("Milk")
                        .HasColumnType("double precision");

                    b.Property<int>("Skins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("YakShop.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<double>("Milk")
                        .HasColumnType("double precision");

                    b.Property<int>("Skins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("YakShop.Models.Yak", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Age")
                        .HasColumnType("double precision");

                    b.Property<double>("AgeLastShaved")
                        .HasColumnType("double precision");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Yak", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
